In [1]:
import numpy as np
import pandas as pd
import gc, os

import lightgbm as lgb
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler

from multiprocessing import cpu_count
from tqdm import tqdm # make loops show a smart progress meter.

from __future__ import print_function

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.svm import SVC



In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import zipfile
!unzip '/content/drive/MyDrive/santander-customer-transaction-prediction.zip'

Archive:  /content/drive/MyDrive/santander-customer-transaction-prediction.zip
  inflating: sample_submission.csv   
  inflating: test.csv                
  inflating: train.csv               


### Help us identify which customers will make a specific transaction in the future, irrespective of the amount of money transacted. 

    ### You are provided with an anonymized dataset containing numeric feature variables, the binary target column, and a string ID_code column.

    ### The task is to predict the value of target column in the test set.

In [4]:
train = pd.read_csv("train.csv").drop(['ID_code'], axis = 1)
test = pd.read_csv("test.csv")

In [5]:
train.head()

target    var_0   var_1    var_2  ...  var_196  var_197  var_198  var_199
0       0   8.9255 -6.7863  11.9081  ...   7.8784   8.5635  12.7803  -1.0914
1       0  11.5006 -4.1473  13.8588  ...   8.1267   8.7889  18.3560   1.9518
2       0   8.6093 -2.7457  12.0805  ...  -6.5213   8.2675  14.7222   0.3965
3       0  11.0604 -2.1518   8.9522  ...  -2.9275  10.2922  17.9697  -8.9996
4       0   9.8369 -1.4834  12.8746  ...   3.9267   9.5031  17.9974  -8.8104

[5 rows x 201 columns]

In [6]:
train.iloc[:][train.isnull() == True]

target  var_0  var_1  var_2  ...  var_196  var_197  var_198  var_199
0          NaN    NaN    NaN    NaN  ...      NaN      NaN      NaN      NaN
1          NaN    NaN    NaN    NaN  ...      NaN      NaN      NaN      NaN
2          NaN    NaN    NaN    NaN  ...      NaN      NaN      NaN      NaN
3          NaN    NaN    NaN    NaN  ...      NaN      NaN      NaN      NaN
4          NaN    NaN    NaN    NaN  ...      NaN      NaN      NaN      NaN
...        ...    ...    ...    ...  ...      ...      ...      ...      ...
199995     NaN    NaN    NaN    NaN  ...      NaN      NaN      NaN      NaN
199996     NaN    NaN    NaN    NaN  ...      NaN      NaN      NaN      NaN
199997     NaN    NaN    NaN    NaN  ...      NaN      NaN      NaN      NaN
199998     NaN    NaN    NaN    NaN  ...      NaN      NaN      NaN      NaN
199999     NaN    NaN    NaN    NaN  ...      NaN      NaN      NaN      NaN

[200000 rows x 201 columns]

In [7]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Columns: 201 entries, target to var_199
dtypes: float64(200), int64(1)
memory usage: 306.7 MB


In [8]:

train.describe()

target          var_0  ...        var_198        var_199
count  200000.000000  200000.000000  ...  200000.000000  200000.000000
mean        0.100490      10.679914  ...      15.870720      -3.326537
std         0.300653       3.040051  ...       3.010945      10.438015
min         0.000000       0.408400  ...       6.299300     -38.852800
25%         0.000000       8.453850  ...      13.829700     -11.208475
50%         0.000000      10.524750  ...      15.934050      -2.819550
75%         0.000000      12.758200  ...      18.064725       4.836800
max         1.000000      20.315000  ...      26.079100      28.500700

[8 rows x 201 columns]

In [9]:
train1 = train.values
test1 = test.values


In [10]:
test1

array([['test_0', 11.0656, 7.7798, ..., 10.72, 15.4722, -8.7197],
       ['test_1', 8.5304, 1.2543, ..., 9.8714, 19.1293, -20.976],
       ['test_2', 5.4827, -10.3581, ..., 7.0618, 19.8956, -23.1794],
       ...,
       ['test_199997', 11.636, 2.2769, ..., 9.1933, 11.7905, -22.2762],
       ['test_199998', 13.5745, -0.5134, ..., 8.1079, 8.7735, -0.2122],
       ['test_199999', 10.4664, 1.807, ..., 10.3378, 14.334000000000001,
        -7.7094]], dtype=object)

In [11]:
#unique_count[index_[count_ == 1], feature]

In [12]:


unique_samples = []
unique_count = np.zeros_like(test1)

for feature in tqdm(range(test1.shape[1])):
    _, index_, count_ = np.unique(test1[:, feature], return_counts=True, return_index=True)
    #print(_) # ordered smallest to largest unique values in the column
    #print(index_) # index of first occurence of each unique value in ordered list _ above in the column
    #print(count_) # count of each unique value in the column
    unique_count[index_[count_ == 1], feature] += 1
    #print(_)
    #print(index_)
    #print(count_ == 1)
    

100%|██████████| 201/201 [00:31<00:00,  6.30it/s]


In [13]:
# Samples which have unique values are real the others are fake
real_samples_indexes = np.argwhere(np.sum(unique_count, axis=1) > 0)[:, 0]
synthetic_samples_indexes = np.argwhere(np.sum(unique_count, axis=1) == 0)[:, 0]
print(len(real_samples_indexes))
print(len(synthetic_samples_indexes))

200000
0


# Find duplicate rows using numpy example below

In [14]:
e = np.array([[1,2,3,9],
              [1,3,4,2],
              [1,2,3,4],
              [1,3,4,2],
              [6,4,1,6]])

unique_counte = np.zeros_like(e)

for feature in tqdm(range(e.shape[1])):
    _e, index_e, count_e = np.unique(e[:, feature], return_counts=True, return_index=True)
    print(_e) # unique values in the column
    print(index_e) # index of first occurence of each unique value in the column
    print(count_e) # count of each unique value in the column
    unique_counte[index_e[count_e == 1], feature] += 1

100%|██████████| 4/4 [00:00<00:00, 1131.46it/s]

[1 6]
[0 4]
[4 1]
[2 3 4]
[0 1 4]
[2 2 1]
[1 3 4]
[4 0 1]
[1 2 2]
[2 4 6 9]
[1 2 4 0]
[2 1 1 1]


In [15]:
# for a column, which unique values have only one count 
print(e)
print(" ")
print(unique_counte)

[[1 2 3 9]
 [1 3 4 2]
 [1 2 3 4]
 [1 3 4 2]
 [6 4 1 6]]
 
[[0 0 0 1]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 0 0]
 [1 1 1 1]]


In [16]:
np.sum(unique_counte, axis=1) # sum rows across columns

array([1, 0, 1, 0, 4])

In [17]:
np.argwhere(np.sum(unique_counte, axis=1) > 0)

array([[0],
       [2],
       [4]])

In [18]:
# rows with at least 1 unique value
np.argwhere(np.sum(unique_counte, axis=1) > 0)[:, 0]

array([0, 2, 4])

In [19]:
# Synthetic or duplicate rows
np.argwhere(np.sum(unique_counte, axis=1) == 0)[:, 0]

array([1, 3])

In [20]:
real_samples_indexes = np.argwhere(np.sum(unique_counte, axis=1) > 0)[:, 0]
synthetic_samples_indexes = np.argwhere(np.sum(unique_counte, axis=1) == 0)[:, 0]
print(len(real_samples_indexes))
print(len(synthetic_samples_indexes))

3
2


In [21]:
#Pandas

edf = pd.DataFrame(e)
edf.duplicated()

0    False
1    False
2    False
3     True
4    False
dtype: bool

# Start HERE for SVM


In [3]:
te_ = pd.read_csv('test.csv').drop(['ID_code'], axis=1).values

unique_samples = []
unique_count = np.zeros_like(te_)
for feature in tqdm(range(te_.shape[1])):
    _, index_, count_ = np.unique(te_[:, feature], return_counts=True, return_index=True)
    unique_count[index_[count_ == 1], feature] += 1

# Samples which have unique values are real the others are fake
real_samples_indexes = np.argwhere(np.sum(unique_count, axis=1) > 0)[:, 0]
synthetic_samples_indexes = np.argwhere(np.sum(unique_count, axis=1) == 0)[:, 0]

print(len(real_samples_indexes))

print(len(synthetic_samples_indexes))


100%|██████████| 200/200 [00:06<00:00, 30.48it/s]


100000
100000


In [4]:
train = pd.read_csv("train.csv")
test  = pd.read_csv("test.csv").drop(synthetic_samples_indexes)


In [5]:
# Balance Training Data Set and Sample rows 

train = train.groupby('target', group_keys=False).apply(lambda x: x.sample(min(len(x), 500), random_state=1994))
train["target"].value_counts()

1    500
0    500
Name: target, dtype: int64

In [6]:
X = train.iloc[:, 2:]
y = train.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.5, random_state=0)


test = test.iloc[:, 1:]

# Set the parameters by cross-validation
tuned_parameters = [{'kernel': ['rbf'], 'gamma': [1e-3, 1e-4],
                     'C': [1, 10, 100, 1000]},
                    {'kernel': ['linear'], 'C': [1, 10, 100, 1000]}]

scores = ['roc_auc']

for score in scores:
    print("# Tuning hyper-parameters for %s" % score)
    print()

    clf = GridSearchCV(SVC(), tuned_parameters, cv=5,
                       scoring=score)
    clf.fit(X_train, y_train)

    print("Best parameters set found on development set:")
    print()
    print(clf.best_params_)
    print()
    print("Grid scores on development set:")
    print()
    means = clf.cv_results_['mean_test_score']
    stds = clf.cv_results_['std_test_score']
    for mean, std, params in zip(means, stds, clf.cv_results_['params']):
        print("%0.3f (+/-%0.03f) for %r"
              % (mean, std * 2, params))
    print()

    print("Detailed classification report:")
    print()
    print("The model is trained on the full development set.")
    print("The scores are computed on the full evaluation set.")
    print()
    y_true, y_pred = y_test, clf.predict(X_test)
    print(classification_report(y_true, y_pred))
    print()

# Tuning hyper-parameters for roc_auc

Best parameters set found on development set:

{'C': 1, 'kernel': 'linear'}

Grid scores on development set:

0.626 (+/-0.109) for {'C': 1, 'gamma': 0.001, 'kernel': 'rbf'}
0.679 (+/-0.081) for {'C': 1, 'gamma': 0.0001, 'kernel': 'rbf'}
0.626 (+/-0.109) for {'C': 10, 'gamma': 0.001, 'kernel': 'rbf'}
0.682 (+/-0.079) for {'C': 10, 'gamma': 0.0001, 'kernel': 'rbf'}
0.626 (+/-0.109) for {'C': 100, 'gamma': 0.001, 'kernel': 'rbf'}
0.682 (+/-0.079) for {'C': 100, 'gamma': 0.0001, 'kernel': 'rbf'}
0.626 (+/-0.109) for {'C': 1000, 'gamma': 0.001, 'kernel': 'rbf'}
0.682 (+/-0.079) for {'C': 1000, 'gamma': 0.0001, 'kernel': 'rbf'}
0.686 (+/-0.124) for {'C': 1, 'kernel': 'linear'}
0.686 (+/-0.124) for {'C': 10, 'kernel': 'linear'}
0.686 (+/-0.124) for {'C': 100, 'kernel': 'linear'}
0.686 (+/-0.124) for {'C': 1000, 'kernel': 'linear'}

Detailed classification report:

The model is trained on the full development set.
The scores are computed on the full evalu